
build:
  version: "1.0"

loans:
  message: "Welcome to Rakesh Bank loans related prod APIs"
  contactDetails:
    name: "Rene copo- Product Owner"
    email: "rene@rakeshbank.com"
  onCallSupport:
    - (453) 392-4829
    - (236) 203-0384